---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04 # AKA trusty
    driver_config:
      image: ubuntu:latest
      platform: ubuntu

suites:
  - name: core
    run_list:
      - recipe[i2d_web::core]
    attributes:
